version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: miniproject_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Essanth@123
      MYSQL_DATABASE: Miniproject
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pEssanth@123"]
      interval: 10s
      timeout: 5s
      retries: 10

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miniproject_dashboard
    restart: always
    ports:
      - "5001:5000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Essanth@123
      DB_NAME: Miniproject
    depends_on:
      mysql:
        condition: service_healthy

  monitor:
    build:
      context: .
      dockerfile: Dockerfile.monitor
    container_name: miniproject_monitor
    restart: always
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: Essanth@123
      DB_NAME: Miniproject
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db_data:
